name: Pesapal Ruby Gem
markdown: redcarpet
pygments: true
baseurl: /pesapal-gem

redcarpet:
  extensions: ['no_intra_emphasis', 'fenced_code_blocks', 'autolink', 'tables']

exclude: ['CNAME', 'Gemfile', 'Gemfile.lock', '*.sublime-project', 'README.md']
