name: Pesapal Ruby Gem
markdown: redcarpet
highlighter: pygments
baseurl: /pesapal-gem

redcarpet:
  extensions: ['no_intra_emphasis', 'fenced_code_blocks', 'autolink', 'tables']

exclude: ['pkg*',
          'CNAME',
          'Gemfile',
          'Gemfile.lock',
          '*.sublime-project',
          'README.md'
        ]
